version: '3.8'

services:
  db_user_service:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: doodle_db_user_service
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data_user_service:/var/lib/mysql

  db_hero_service:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: doodle_db_hero_service
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - db_data_hero_service:/var/lib/mysql

  db_dungeon_service:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: doodle_db_dungeon_service
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3308:3306"
    volumes:
      - db_data_dungeon_service:/var/lib/mysql

  db_battle_service:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: doodle_db_battle_service
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3309:3306"
    volumes:
      - db_data_battle_service:/var/lib/mysql

  db_monster_service:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: doodle_db_monster_service
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3310:3306"
    volumes:
      - db_data_monster_service:/var/lib/mysql

volumes:
  db_data_user_service:
  db_data_hero_service:
  db_data_dungeon_service:
  db_data_battle_service:
  db_data_monster_service:
